### ISSUE TITLE
Add a command to publish to WAPM?

### ISSUE THREAD

**Issue by jedisct1** [alexcrichton/cargo-wasi#14]
It would be great to include a command to directly sign and publish the package to WAPM.

**Comment by alexcrichton** [comment]
Thanks for the report! I'm personally wary to do this because I feel like the deployment story for `*.wasm` modules using WASI is still somewhat in flux. I'd prefer to not add too much experimental support to this subcommand just yet, and I'd prefer to wait and see what the multi-module and/or deployment story for wasm modules turns out to be in the future.

All that to say that eventually I think this'd be a great feature to have! I think though at this time it's a bit early to add support, so I'm going to close.
